# CIS 5370 Final Project

## Project 1 - Intrusion Detection for Industrial Control Systems

- Kyle Brindle
- Rayhan Alcena

In [2]:
from pathlib import Path
import os
import pandas as pd
import numpy as np
import sklearn
from nfstream import NFStreamer

## Loading Files

In [ ]:
# Base path to the datasets
BASE_PATH = Path.cwd() / "data/SWaT_A6_Dec_2019/"
SENSOR_READINGS_PATH = BASE_PATH / "csv/"
NETWORK_READINGS_PATH = BASE_PATH / "pcap/"

# Sensor Readings CSV/XLSX file paths
dec_2019_file_path = SENSOR_READINGS_PATH / "Dec2019.xlsx"

# Network Readings CSV/XLSX file paths
#test_converted_pcap_file_path = NETWORK_READINGS_PATH / "converted.csv"

# Loading the CSV/XLSX files (We had to skip the first 9 rows (0-9))
sensor_readings_df = pd.read_excel(dec_2019_file_path, skiprows=9)

# Converts all pcaps in a directory into CSV files with network flows
# i = 0;
# for file_name in os.listdir(NETWORK_READINGS_PATH):
#     if file_name.endswith(".pcap"):
#         converted_pcap_file_path = NETWORK_READINGS_PATH / ("0" + str(i) + "_converted.csv")
#         print(f"Converting {file_name}")
#         streamer = NFStreamer(source = NETWORK_READINGS_PATH / file_name).to_csv(converted_pcap_file_path)
#         print(f"{file_name} converted with {streamer} flows")
#         i = i + 1

#Converts a singular pcap into a CSV file with network flows
#streamer = NFStreamer(source=NETWORK_READINGS_PATH / "Dec2019_00001_20191206102207.pcap").to_csv(path=test_converted_pcap_file_path)
#print(f"Exported {streamer} flows")

#network_readings_df = pd.read_csv(test_converted_pcap_file_path)

Converting Dec2019_00000_20191206100500.pcap
Dec2019_00000_20191206100500.pcap converted with 308606 flows
Converting Dec2019_00001_20191206102207.pcap
Dec2019_00001_20191206102207.pcap converted with 167936 flows
Converting Dec2019_00002_20191206103000.pcap
Dec2019_00002_20191206103000.pcap converted with 345025 flows
Converting Dec2019_00003_20191206104500.pcap
Dec2019_00003_20191206104500.pcap converted with 343900 flows
Converting Dec2019_00004_20191206110000.pcap
Dec2019_00004_20191206110000.pcap converted with 343806 flows
Converting Dec2019_00005_20191206111500.pcap
Dec2019_00005_20191206111500.pcap converted with 344370 flows
Converting Dec2019_00006_20191206113000.pcap
Dec2019_00006_20191206113000.pcap converted with 308859 flows
Converting Dec2019_00007_20191206114500.pcap
Dec2019_00007_20191206114500.pcap converted with 309916 flows
Converting Dec2019_00008_20191206120000.pcap
Dec2019_00008_20191206120000.pcap converted with 310579 flows
Converting Dec2019_00009_20191206121500.pcap
Dec2019_00009_20191206121500.pcap converted with 306889 flows
Converting Dec2019_00010_20191206123000.pcap
Dec2019_00010_20191206123000.pcap converted with 308863 flows
Converting Dec2019_00011_20191206124500.pcap
Dec2019_00011_20191206124500.pcap converted with 309340 flows
Converting Dec2019_00012_20191206130000.pcap
Dec2019_00012_20191206130000.pcap converted with 306362 flows
Converting Dec2019_00013_20191206131500.pcap
Dec2019_00013_20191206131500.pcap converted with 308052 flows
Converting Dec2019_00014_20191206133000.pcap
Dec2019_00014_20191206133000.pcap converted with 306281 flows

## Preprocessing

## Sensor Readings Evaluations

In [8]:
sensor_readings_df.head(10)

,t_stamp,P1_STATE,LIT101.Pv,FIT101.Pv,MV101.Status,P101.Status,P102.Status,P2_STATE,FIT201.Pv,AIT201.Pv,...,FIT601.Pv,P601.Status,P602.Status,P603.Status,LSH601.Alarm,LSL601.Alarm,LSH602.Alarm,LSL602.Alarm,LSH603.Alarm,LSL603.Alarm
0,2019-12-06 10:05:00,3,658.661255,0.0,1,2.0,1,2,2.313523,35.215330,...,0.000256,2,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
1,2019-12-06 10:05:01,3,659.171600,0.0,1,2.0,1,2,2.311857,35.215330,...,0.000256,2,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
2,2019-12-06 10:05:02,3,659.681800,0.0,1,2.0,1,2,2.311601,35.215330,...,0.000256,2,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
3,2019-12-06 10:05:03,3,660.349100,0.0,1,2.0,1,2,2.310448,35.215330,...,0.000256,2,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
4,2019-12-06 10:05:04,3,660.780945,0.0,1,2.0,1,2,2.310448,35.215330,...,0.000256,2,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
5,2019-12-06 10:05:05,3,661.016400,0.0,1,2.0,1,2,2.311088,35.087160,...,0.000256,2,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
6,2019-12-06 10:05:06,3,661.055700,0.0,1,2.0,1,2,2.316086,34.958984,...,0.000256,2,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
7,2019-12-06 10:05:07,3,661.330444,0.0,1,2.0,1,2,2.317624,34.958984,...,0.000256,2,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
8,2019-12-06 10:05:08,3,661.369700,0.0,1,2.0,1,2,2.321469,34.958984,...,0.000256,2,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
9,2019-12-06 10:05:09,3,661.644500,0.0,1,2.0,1,2,2.325057,34.958984,...,0.000256,2,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active

## Network Readings Evaluations

In [4]:
network_readings_df.head(100000)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_bytes,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.1.219,00:15:5d:01:57:90,00:15:5d,35572,192.168.1.200,00:15:5d:01:9a:49,00:15:5d,443,...,598,TLS,Web,0,6,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.1.219,00:15:5d:01:57:90,00:15:5d,35542,192.168.1.200,00:15:5d:01:9a:49,00:15:5d,443,...,70,TLS,Web,1,1,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.1.220,00:15:5d:01:57:8a,00:15:5d,41926,192.168.1.200,00:15:5d:01:9a:49,00:15:5d,443,...,132,TLS,Web,1,1,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.1.200,00:15:5d:01:9a:49,00:15:5d,443,192.168.1.220,00:15:5d:01:57:8a,00:15:5d,41932,...,0,TLS,Web,1,1,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.1.219,00:15:5d:01:57:90,00:15:5d,35536,192.168.1.200,00:15:5d:01:9a:49,00:15:5d,443,...,66,TLS,Web,1,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,0,192.168.1.200,00:15:5d:01:9a:49,00:15:5d,443,192.168.1.219,00:15:5d:01:57:90,00:15:5d,58308,...,1533,TLS,Web,0,6,NaN,t12i490500_730fb1b0ac6a_a1e935682795,4192c0a946c5bd9b544b4656d9f624a4,NaN,NaN
99996,99996,0,192.168.1.200,00:15:5d:01:9a:49,00:15:5d,443,192.168.1.220,00:15:5d:01:57:8a,00:15:5d,40456,...,1361,TLS,Web,0,6,NaN,t12i490500_730fb1b0ac6a_a1e935682795,4192c0a946c5bd9b544b4656d9f624a4,NaN,NaN
99997,99997,0,192.168.1.200,00:15:5d:01:9a:49,00:15:5d,443,192.168.1.219,00:15:5d:01:57:90,00:15:5d,58210,...,1533,TLS,Web,0,6,NaN,t12i490500_730fb1b0ac6a_a1e935682795,4192c0a946c5bd9b544b4656d9f624a4,NaN,NaN
99998,99998,0,192.168.1.200,00:15:5d:01:9a:49,00:15:5d,443,192.168.1.219,00:15:5d:01:57:90,00:15:5d,34192,...,1295,TLS,Web,0,6,NaN,t12i490500_730fb1b0ac6a_a1e935682795,4192c0a946c5bd9b544b4656d9f624a4,NaN,NaN
99999,99999,0,192.168.1.200,00:15:5d:01:9a:49,00:15:5d,443,192.168.1.219,00:15:5d:01:57:90,00:15:5d,58280,...,1393,TLS,Web,0,6,NaN,t12i490500_730fb1b0ac6a_a1e935682795,4192c0a946c5bd9b544b4656d9f624a4,NaN,NaN

## Isolation Forest